dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test mixnet --keepdb 
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: egc-app-decide-pro
  strategy: git
  api_key: 
    secure: HlT8L9I2gWshXmsvDpriam9PK5Kl6XtYTqlc/KozqQkSjmVhlSZsIHD3na0B1erGZ/meonMXDW1hovYKesluXPFN0e2MqVMUyOol/b2RL2Rnn+bEj1nN4l6I7R0NtAGuHtze57JGMOgqgDw3SiwbYGDr4YqHpxI8lJjBbMl4799R5u0jtWB+70cov3dvIEvTcgWvylLnIIsF+ie0TUwdHpuSXj/gfv4eRuFLWPfm+USkjDkZYBZXr++pNuUfpg+Z4H6roJlVozf7t7MHbvuX3Wq03/8x4xYG0WJ6PEL1oFFYX11fgZCgVdK1HBDFwMU5I5X0wunSFtp8bwLLEkgPKk/A2StN56IMV1HbRTxWSY85TSM2TE1y5KQTPI0qq8wcEcwFsjLpf/bB9kjZO5tnnvM5tcPbFHZy/hwAOQWEQuwmXEkju6dpKsEdd3KJczLPLTmLCoFuvxpl+itdAl/kB224xcmlKvddoH3MC7qu8kCbrcihgEL+HnYh0MzgFlZAHfpDZeQuOlFkuAbd2pCOjOz3mJxjKRSXAjeB5Cbm0Hz1qXEq7lxIgT6RpFpewlEgCLcfq58UJfUw4N/hZQa6+4erojXn0diYu03ttnQgt4nb1FcoH7Z8MudOfkD2zPgPNHzCCr5iaH9ng05OsFkvt2ORfBz/7vXjTnJBPJyjkUA=
